### ISSUE TITLE
Corporate Invoice Followup

### ISSUE THREAD

**Issue by varmab** [varmab/codingsastra#2]

**Comment by nithinvarmadandu** [comment]
I have sent reminder emails and also made follow up calls today(10-07-19).

Been following up on a daily basis,

**Comment by nithinvarmadandu** [comment]
Akrivia invoice is still pending. been following up on a daily basis.

Inventrax invoice is cleared.

**Comment by nithinvarmadandu** [comment]
Akrivia Invoice cleared on 31-07-19.
